package com.jeremybrooks.chess;

/**
 * Implement this to define your own move generator.
 * 
 * @author jeremy
 *
 */
public interface Generator {

	/**
	 * Populate the moves argument with moves available from the game state argument.
	 * 
	 * GameState contains the array of moves that has been generated.
	 * Since moves can be generated by different generators game state
	 * has the g.legalMoves[depth] slot available for this purpose.  It
	 * is indexed by the current depth.
	 *
	 * @param g the game state
	 * @param moves the array that will be populated with generated moves
	 * @param side the side to move
	 * @param depth the depth at which these moves will be generated
	 * @return the number of moves generated
	 */
	public int generate(GameState g, int[] moves, int side, int depth);
}
