package com.jeremybrooks.chess;

import static com.jeremybrooks.chess.Bitmap.*;

/**
 * Implement this to define your own move generator.
 * 
 * @author jeremy
 *
 */
public interface Generator {

	/**
	 * Populate the moves argument with moves available from the game state argument.
	 * 
	 * GameState contains the array of moves that has been generated.
	 * Since moves can be generated by different generators game state
	 * has the g.legalMoves[depth] slot available for this purpose.  It
	 * is indexed by the current depth.
	 *
	 * @param g the game state
	 * @param moves the array that will be populated with generated moves
	 * @param side the side to move
	 * @param depth the depth at which these moves will be generated
	 * @return the number of moves generated
	 */
	public int generate(int[] moves, int side, int depth);

	public boolean isAttacked(GameState g, int side, int sq);
	
	// Returns a bitbrd of the pieces (excluding the king) attacking 
	// "square".  "side" represents the color/side whose pieces we want to
	// see that are under attack.
	// To see all the black pieces attacking e4 do this:
	//
    //	    attacks = Attackers(g, Color.WHITE, E4);
	//
	// To see all the white pieces attacking g8 do this;
	//
    //	    attacks = Attackers(g, Color.BLACK, G8);
	//
	//NOTE: the king is not included in the attackers
	public long attackers(GameState g, int sideUnderAttack, int squareUnderAttack);

	public boolean canWhiteShortCastle(GameState g, int side);

	public boolean canWhiteLongCastle(GameState g, int side);

	public boolean canBlackShortCastle(GameState g, int side);

	public boolean canBlackLongCastle(GameState g, int side);

	public void setGameState(GameState gameState);
}